/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIFrame1.java
 *
 * Created on 2011-5-6, 23:54:04
 */

package Presentation;

import Presentation.TimeSeriesChart.DataGenerator;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Label;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class MainWindow extends javax.swing.JFrame {

    /** Creates new form UIFrame1 */
    public MainWindow() {

//        TimeSeriesChart panel = new TimeSeriesChart(12000,false);
//        panel.new DataGenerator(90).start();
//        panel.setSize(400, 200);
//        panel.setLocation(0,170);
//        this.add(panel);
//        Label a = new Label("Hello world");
//        this.add(a);
//        a.setSize(400, 200);
//        a.setLocation(0,200);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("流量监控系统");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
