 git blame ./Database/Database.java >> result.txt 
 git blame ./Database/DatabaseAppender.java >> result.txt 
 git blame ./Database/DatabaseThread.java >> result.txt 
 git blame ./Database/Flow.java >> result.txt 
 git blame ./Database/IDatabaseProxy.java >> result.txt 
 git blame ./Logic/Filters/AbstractPacketFilter.java >> result.txt 
 git blame ./Logic/Filters/CernetAttribute.java >> result.txt 
 git blame ./Logic/Filters/CernetPacketFilter.java >> result.txt 
 git blame ./Logic/Filters/CernetReader.java >> result.txt 
 git blame ./Logic/Filters/FilterFactory.java >> result.txt 
 git blame ./Logic/Filters/HttpFilter.java >> result.txt 
 git blame ./Logic/Filters/IPacketFilter.java >> result.txt 
 git blame ./Logic/Filters/TcpFilter.java >> result.txt 
 git blame ./Logic/History/FlowHistoryInfo.java >> result.txt 
 git blame ./Logic/History/HistoryCompressThread.java >> result.txt 
 git blame ./Logic/History/HistoryInfo.java >> result.txt 
 git blame ./Logic/History/MostFlowedSiteHistoryInfo.java >> result.txt 
 git blame ./Logic/History/MostVisitedSiteHistoryInfo.java >> result.txt 
 git blame ./Logic/History/ProcessCompleteListener.java >> result.txt 
 git blame ./Logic/History/ProcessThread.java >> result.txt 
 git blame ./Logic/History/ProtocolHistoryInfo.java >> result.txt 
 git blame ./Logic/History/RawPacketHistoryInfo.java >> result.txt 
 git blame ./Logic/History/TimeAttributeHistoryInfo.java >> result.txt 
 git blame ./Logic/PacketPool/IPacketPool.java >> result.txt 
 git blame ./Logic/PacketPool/IPacketPoolEvent.java >> result.txt 
 git blame ./Logic/PacketPool/IPacketPoolEventListener.java >> result.txt 
 git blame ./Logic/PacketPool/PacketPool.java >> result.txt 
 git blame ./Logic/PacketPool/PacketPoolEvent.java >> result.txt 
 git blame ./Logic/PacketPool/PacketPoolEventListenerStub.java >> result.txt 
 git blame ./Network/AbstractPacket.java >> result.txt 
 git blame ./Network/INetwork.java >> result.txt 
 git blame ./Network/IPacket.java >> result.txt 
 git blame ./Network/IPacketListener.java >> result.txt 
 git blame ./Network/ListenThread.java >> result.txt 
 git blame ./Network/Network.java >> result.txt 
 git blame ./Network/Packet.java >> result.txt 
 git blame ./Network/PacketListenerStub.java >> result.txt 
 git blame ./Network/PacketStub.java >> result.txt 
 git blame ./Presentation/Main.java >> result.txt 
 git blame ./Presentation/PieChart.java >> result.txt 
 git blame ./Presentation/SmallWindow.java >> result.txt 
 git blame ./Presentation/Statics/AbstractStaticsPage.java >> result.txt 
 git blame ./Presentation/Statics/AnalysisChartPage.java >> result.txt 
 git blame ./Presentation/Statics/DataCompressPage.java >> result.txt 
 git blame ./Presentation/Statics/DataCompressPanel.java >> result.txt 
 git blame ./Presentation/Statics/DynamicFlowChartPage.java >> result.txt 
 git blame ./Presentation/Statics/HistoryFlowPage.java >> result.txt 
 git blame ./Presentation/Statics/HistoryFlowPanel.java >> result.txt 
 git blame ./Presentation/Statics/IStaticsPage.java >> result.txt 
 git blame ./Presentation/Statics/StaticsMain.java >> result.txt 
 git blame ./Presentation/Statics/TestPage.java >> result.txt 
 git blame ./Presentation/Statics/TestPage2.java >> result.txt 
 git blame ./Presentation/Statics/TimeAttributePage.java >> result.txt 
 git blame ./Presentation/Statics/TimeAttributePanel.java >> result.txt 
 git blame ./Presentation/Statics/TimeSelectPanel.java >> result.txt 
 git blame ./Presentation/Statics/TimeSeriesChartPanel.java >> result.txt 
 git blame ./Presentation/TrayIconWindow.java >> result.txt 